/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.CardLayout;
import Controller.VCRScontroller;
import javax.swing.JOptionPane;
import Model.Voter;

/**
 *
 * @author Admin
 */
public class ViewVCRS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewVCRS.class.getName());
    private VCRScontroller controller;


    /**
     * Creates new form ViewVCRS
     */
    public ViewVCRS() {
    initComponents();
    controller = new VCRScontroller();
    }
    
   private void loadTable()
  {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) MainTable.getModel();
    model.setRowCount(0); // clear old rows
    
    int front = controller.getFront();
    int rear = controller.getRear();
    
    // Check if queue is empty
    if (front == -1 || front > rear) {
        return;
    }
    
    // Load voters from queue (front to rear)
    Model.Voter[] votersQueue = controller.getVotersQueue();
    for (int i = front; i <= rear; i++) {
        if (votersQueue[i] != null) {
            Model.Voter v = votersQueue[i];
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getFather(),
                v.getMother(),
                v.getGrandfather(),
                v.getDOB(),
                v.getPhone()
            });
        }
    }
}
    
private void loadDeletedTable() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) DeletedTable.getModel();
    model.setRowCount(0);
    
    int deletedTop = controller.getDeletedTop();
    
    // Load from stack (top to bottom - most recent first)
    Voter[] deletedStack = controller.getDeletedStack();
    for (int i = deletedTop; i >= 0; i--) {
        if (deletedStack[i] != null) {
            Voter v = deletedStack[i];
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getDOB(),
                v.getPhone()
            });
        }
    }
}
    
 private void loadVerifiedTable() {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) VerifiedTable.getModel();
    model.setRowCount(0);
    
    int verifiedTop = controller.getVerifiedTop();
    
    // Load from stack (top to bottom - most recent first)
    Voter[] verifiedStack = controller.getVerifiedStack();
    for (int i = verifiedTop; i >= 0; i--) {
        if (verifiedStack[i] != null) {
            Voter v = verifiedStack[i];
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getDOB(),
                v.getPhone(),
                "Verified"
            });
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        bgSortOrder = new javax.swing.ButtonGroup();
        Banner = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        homeRegisterBtn = new javax.swing.JButton();
        homeUpdateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adminLoginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registrationPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        txtcitizenship = new javax.swing.JTextField();
        txtfather = new javax.swing.JTextField();
        txtmother = new javax.swing.JTextField();
        txtgrandfather = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        rbDescending = new javax.swing.JRadioButton();
        rbAscending = new javax.swing.JRadioButton();
        cmbSortBy = new javax.swing.JComboBox<>();
        cmbSearchBy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        HistoryBtn = new javax.swing.JButton();
        VerifyBtn = new javax.swing.JButton();
        SortMainTableBtn = new javax.swing.JButton();
        BinarySearchBtn = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        UpdateBtn = new javax.swing.JButton();
        txtname1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtfather1 = new javax.swing.JTextField();
        txtmother1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtgrandfather1 = new javax.swing.JTextField();
        txtdob1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtphone1 = new javax.swing.JTextField();
        txtSearchCitizenship = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnFindActionPerformed = new javax.swing.JButton();
        BackUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DeletedTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        VerifiedTable = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        SortDeletedTableBtn = new javax.swing.JButton();
        SortVerifiedTableBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 755));

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/UpperBanner.png"))); // NOI18N

        MainPanel.setPreferredSize(new java.awt.Dimension(850, 560));
        MainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 204, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("   VOTER CARD REGISTRATION   ");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        homeRegisterBtn.setBackground(new java.awt.Color(255, 204, 204));
        homeRegisterBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        homeRegisterBtn.setText("Register");
        homeRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeRegisterBtnActionPerformed(evt);
            }
        });

        homeUpdateBtn.setBackground(new java.awt.Color(255, 255, 204));
        homeUpdateBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        homeUpdateBtn.setText("Update");
        homeUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeUpdateBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/NepalMap.png"))); // NOI18N

        adminLoginBtn.setBackground(new java.awt.Color(102, 255, 204));
        adminLoginBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        adminLoginBtn.setText("LOGIN");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/UserIcon.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DownBanner.png"))); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adminLoginBtn)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(homeRegisterBtn)
                                .addGap(18, 18, 18)
                                .addComponent(homeUpdateBtn)
                                .addGap(30, 30, 30)))))
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(homeRegisterBtn)
                            .addComponent(homeUpdateBtn))
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminLoginBtn))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        MainPanel.add(homePanel, "card2");

        registrationPanel.setBackground(new java.awt.Color(204, 204, 204));
        registrationPanel.setPreferredSize(new java.awt.Dimension(850, 540));
        registrationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton5.setText("Back ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        registrationPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 121, -1));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        txtname.setBackground(new java.awt.Color(204, 255, 255));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txtcitizenship.setBackground(new java.awt.Color(204, 255, 255));
        txtcitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcitizenshipActionPerformed(evt);
            }
        });

        txtfather.setBackground(new java.awt.Color(204, 255, 255));
        txtfather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfatherActionPerformed(evt);
            }
        });

        txtmother.setBackground(new java.awt.Color(204, 255, 255));

        txtgrandfather.setBackground(new java.awt.Color(204, 255, 255));

        txtdob.setBackground(new java.awt.Color(204, 255, 255));

        txtphone.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel11.setText("Name");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel17.setText("Citizenship");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel12.setText("Father's Name");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel14.setText("Mother's Name");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel15.setText("GrandFather's Name");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        jLabel13.setText("Date of Birth");

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 12)); // NOI18N
        jLabel16.setText("Phone Number");

        RegisterBtn.setBackground(new java.awt.Color(153, 255, 153));
        RegisterBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        RegisterBtn.setText("Register ");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgrandfather, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmother, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfather, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtgrandfather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(RegisterBtn)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        registrationPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 360, 340));

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 153));
        jLabel27.setText("REGISTRATION");
        registrationPanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 270, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/BGREG.png"))); // NOI18N
        registrationPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        MainPanel.add(registrationPanel, "card3");

        loginPanel.setBackground(new java.awt.Color(153, 204, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton6.setText("Back ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        loginPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 90, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/ECM.png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Admin Login");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(102, 255, 204));
        btnLogin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("ShowPassword");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 65, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/BGlogin.png"))); // NOI18N
        loginPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        MainPanel.add(loginPanel, "card4");

        adminPanel.setBackground(new java.awt.Color(153, 204, 255));
        adminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgSortOrder.add(rbDescending);
        rbDescending.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rbDescending.setText("Descending");
        rbDescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDescendingActionPerformed(evt);
            }
        });
        adminPanel.add(rbDescending, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        bgSortOrder.add(rbAscending);
        rbAscending.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        rbAscending.setSelected(true);
        rbAscending.setText("Ascending");
        adminPanel.add(rbAscending, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        cmbSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "DOB" }));
        cmbSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSortByActionPerformed(evt);
            }
        });
        adminPanel.add(cmbSortBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 90, -1));

        cmbSearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "CitizenshipID" }));
        adminPanel.add(cmbSearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 90, -1));

        MainTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Citizenship", "Father's Name", "Mother's Name", "GrandFather's Name", "DateofBirth", "PhoneNumber"
            }
        ));
        jScrollPane1.setViewportView(MainTable);

        adminPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 821, 347));

        DeleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        DeleteBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        adminPanel.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 40));

        HistoryBtn.setBackground(new java.awt.Color(153, 255, 255));
        HistoryBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        HistoryBtn.setText("History");
        HistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBtnActionPerformed(evt);
            }
        });
        adminPanel.add(HistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 100, 40));

        VerifyBtn.setBackground(new java.awt.Color(102, 255, 102));
        VerifyBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        VerifyBtn.setForeground(new java.awt.Color(255, 255, 255));
        VerifyBtn.setText("Verify");
        VerifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyBtnActionPerformed(evt);
            }
        });
        adminPanel.add(VerifyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 40));

        SortMainTableBtn.setText("Sort");
        SortMainTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortMainTableBtnActionPerformed(evt);
            }
        });
        adminPanel.add(SortMainTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        BinarySearchBtn.setText("Search");
        BinarySearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinarySearchBtnActionPerformed(evt);
            }
        });
        adminPanel.add(BinarySearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        adminPanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 180, -1));

        jButton7.setBackground(new java.awt.Color(255, 102, 102));
        jButton7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton7.setText("Back ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        adminPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 90, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/BGadmin.png"))); // NOI18N
        adminPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        MainPanel.add(adminPanel, "card5");

        updatePanel.setBackground(new java.awt.Color(153, 204, 255));
        updatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateBtn.setBackground(new java.awt.Color(102, 255, 102));
        UpdateBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        updatePanel.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 421, 90, 30));

        txtname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        txtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname1ActionPerformed(evt);
            }
        });
        updatePanel.add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 187, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel19.setText("Name");
        updatePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 74, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel21.setText("Father's Name");
        updatePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        txtfather1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        txtfather1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfather1ActionPerformed(evt);
            }
        });
        updatePanel.add(txtfather1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 187, -1));

        txtmother1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        updatePanel.add(txtmother1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel22.setText("Mother's Name");
        updatePanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel23.setText("GrandFather's Name");
        updatePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtgrandfather1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        updatePanel.add(txtgrandfather1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 189, -1));

        txtdob1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        txtdob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdob1ActionPerformed(evt);
            }
        });
        updatePanel.add(txtdob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel24.setText("Date of Birth");
        updatePanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 88, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel25.setText("Phone Number");
        updatePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, -1));

        txtphone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        updatePanel.add(txtphone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, -1));

        txtSearchCitizenship.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 3));
        txtSearchCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCitizenshipActionPerformed(evt);
            }
        });
        updatePanel.add(txtSearchCitizenship, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 35, 168, -1));

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel26.setText("Search:");
        updatePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 38, 43, -1));

        btnFindActionPerformed.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        btnFindActionPerformed.setText("Find");
        btnFindActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformedActionPerformed(evt);
            }
        });
        updatePanel.add(btnFindActionPerformed, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 36, -1, 22));

        BackUpdate.setBackground(new java.awt.Color(255, 102, 102));
        BackUpdate.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        BackUpdate.setText("Back");
        BackUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackUpdateActionPerformed(evt);
            }
        });
        updatePanel.add(BackUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/BGupdate.png"))); // NOI18N
        updatePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        MainPanel.add(updatePanel, "card6");

        historyPanel.setBackground(new java.awt.Color(153, 204, 255));
        historyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/VerifiedIcon.png"))); // NOI18N
        historyPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 40, 40));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DeletedIcon.png"))); // NOI18N
        historyPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 40));

        DeletedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "CitizenshipID", "DOB", "Phone"
            }
        ));
        jScrollPane2.setViewportView(DeletedTable);

        historyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 366, -1));

        VerifiedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "CitizenshipID", "DOB", "Phone", "Status"
            }
        ));
        jScrollPane3.setViewportView(VerifiedTable);

        historyPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 60, 408, -1));

        jButton10.setBackground(new java.awt.Color(255, 102, 102));
        jButton10.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton10.setText("Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        historyPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 100, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 153));
        jLabel28.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Deleted");
        historyPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, 30));

        jLabel29.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel29.setText("Verified");
        historyPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 132, 31));

        SortDeletedTableBtn.setBackground(new java.awt.Color(255, 204, 204));
        SortDeletedTableBtn.setText("Sort By Name");
        SortDeletedTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortDeletedTableBtnActionPerformed(evt);
            }
        });
        historyPanel.add(SortDeletedTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        SortVerifiedTableBtn.setBackground(new java.awt.Color(204, 255, 204));
        SortVerifiedTableBtn.setText("Sort By Name");
        SortVerifiedTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortVerifiedTableBtnActionPerformed(evt);
            }
        });
        historyPanel.add(SortVerifiedTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/BGhistory.png"))); // NOI18N
        historyPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        MainPanel.add(historyPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card5");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void BackUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackUpdateActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card2");
    }//GEN-LAST:event_BackUpdateActionPerformed

    private void btnFindActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformedActionPerformed
        String citizenshipId = txtSearchCitizenship.getText();

        Voter v = controller.findVoterByCitizenship(citizenshipId);

        if (v == null) {
            JOptionPane.showMessageDialog(this, "Voter not found");
            return;
        }

        txtname1.setText(v.getName());
        txtfather1.setText(v.getFather());
        txtmother1.setText(v.getMother());
        txtgrandfather1.setText(v.getGrandfather());
        txtdob1.setText(String.valueOf(v.getDOB()));
        txtphone1.setText(String.valueOf(v.getPhone()));

        JOptionPane.showMessageDialog(this, "Voter loaded. You may update details.");
    }//GEN-LAST:event_btnFindActionPerformedActionPerformed

    private void txtSearchCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCitizenshipActionPerformed

    private void txtdob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdob1ActionPerformed

    private void txtfather1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfather1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfather1ActionPerformed

    private void txtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1ActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        try {
            boolean updated = controller.updateVoter(
                txtSearchCitizenship.getText(),
                txtname1.getText(),
                txtfather1.getText(),
                txtmother1.getText(),
                txtgrandfather1.getText(),
                txtdob1.getText(),
                txtphone1.getText()
            );

            if (updated) {
                JOptionPane.showMessageDialog(this, "Voter updated successfully");

                loadTable(); // refresh admin table
            } else {
                JOptionPane.showMessageDialog(this, "Update failed");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age must be a number");
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void VerifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyBtnActionPerformed

        int selectedRow = MainTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a voter");
            return;
        }

        String citizenshipId =
        MainTable.getValueAt(selectedRow, 1).toString(); // citizenship column

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to verify this voter?",
            "Confirm Verification",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean verified = controller.verifyVoter(citizenshipId);

        if (verified) {
            JOptionPane.showMessageDialog(this, "Voter verified successfully");

            loadTable();           // Active voters
            loadVerifiedTable();   // Verified voters
        }
    }//GEN-LAST:event_VerifyBtnActionPerformed

    private void HistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBtnActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card7");
    }//GEN-LAST:event_HistoryBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int selectedRow = MainTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a voter");
            return;
        }

        String citizenshipId =
        MainTable.getValueAt(selectedRow, 1).toString(); // column index for citizenship

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this voter?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean deleted = controller.deleteVoter(citizenshipId);

        if (deleted) {
            JOptionPane.showMessageDialog(this, "Voter deleted successfully");
            loadTable();
            loadDeletedTable();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected())
        {
            jPasswordField1.setEchoChar((char)0);
        }
        else
        {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = jTextField2.getText();
        String password = new String(jPasswordField1.getPassword());

        if (controller.login(email, password))
        {
            JOptionPane.showMessageDialog(this, "Login Successful");

            // open ADMIN PANEL
            CardLayout cl = (CardLayout) MainPanel.getLayout();
            cl.show(MainPanel, "card5"); // admin dashboard panel
            loadTable();
        } 
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Login");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // Required fields
        if (txtname.getText().trim().isEmpty() ||
            txtcitizenship.getText().trim().isEmpty() ||
            txtfather.getText().trim().isEmpty() ||
            txtmother.getText().trim().isEmpty() ||
            txtgrandfather.getText().trim().isEmpty() ||
            txtdob.getText().trim().isEmpty() ||
            txtphone.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields are required");
            return;
        }

        // Phone validation
        if (!txtphone.getText().matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this, "Phone number must be exactly 10 digits");
            return;
        }

        // DOB format validation
        String dob = txtdob.getText().trim();

        if (!dob.matches("^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(19|20)\\d{2}$"))
        {
            JOptionPane.showMessageDialog(this, "DOB must be in DD-MM-YYYY format");
            return;
        }

        // DOB year validation
        int year = Integer.parseInt(dob.substring(6, 10));
        if (year > 2008)
        {
            JOptionPane.showMessageDialog(this, "DOB year must not be greater than 2008");
            return;
        }

        try {
            Voter v = new Voter(
                txtname.getText().trim(),
                txtcitizenship.getText().trim(),
                txtfather.getText().trim(),
                txtmother.getText().trim(),
                txtgrandfather.getText().trim(),
                dob,
                txtphone.getText().trim()
            );

            controller.addVoter(v);
            JOptionPane.showMessageDialog(this, "Voter Registered");
            loadTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong");
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void txtfatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfatherActionPerformed

    private void txtcitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcitizenshipActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card2");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SortMainTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortMainTableBtnActionPerformed
    // Get selected sort field from dropdown (JComboBox)
    String sortBy = (String) cmbSortBy.getSelectedItem();
    
    if (sortBy == null) {
        JOptionPane.showMessageDialog(this, "Please select a sort option");
        return;
    }
    
    // Check which radio button is selected (Ascending or Descending)
    boolean isAscending = rbAscending.isSelected();
    
    Voter[] sortedVoters = null;
    String message = "";
    
    // Sort based on dropdown and radio button selection
    if (sortBy.equals("Name")) {
        if (isAscending) {
            sortedVoters = controller.insertionSortByName();
            message = "MainTable sorted by Name (A→Z) using Insertion Sort";
        } else {
            sortedVoters = controller.insertionSortByNameDescending();
            message = "MainTable sorted by Name (Z→A) using Insertion Sort";
        }
    } else if (sortBy.equals("DOB")) {
        if (isAscending) {
            sortedVoters = controller.insertionSortByDOB();
            message = "MainTable sorted by DOB (Oldest→Newest) using Insertion Sort";
        } else {
            sortedVoters = controller.insertionSortByDOBDescending();
            message = "MainTable sorted by DOB (Newest→Oldest) using Insertion Sort";
        }
    }
    
    if (sortedVoters == null || sortedVoters.length == 0) {
        JOptionPane.showMessageDialog(this, "No voters to sort");
        return;
    }
    
    // Load sorted data into MainTable
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) MainTable.getModel();
    model.setRowCount(0);
    
    for (Voter v : sortedVoters) {
        if (v != null) {
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getFather(),
                v.getMother(),
                v.getGrandfather(),
                v.getDOB(),
                v.getPhone()
            });
        }
    }
    
    JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_SortMainTableBtnActionPerformed

    private void SortDeletedTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortDeletedTableBtnActionPerformed
         Voter[] sortedVoters = controller.selectionSortDeletedByName();
    
    if (sortedVoters.length == 0) {
        JOptionPane.showMessageDialog(this, "No deleted voters to sort");
        return;
    }
    
    // Load sorted data into DeletedTable
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) DeletedTable.getModel();
    model.setRowCount(0);
    
    for (Voter v : sortedVoters) {
        if (v != null) {
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getDOB(),
                v.getPhone()
            });
        }
    }
    
    JOptionPane.showMessageDialog(this, "DeletedTable sorted by Name using Selection Sort");
    }//GEN-LAST:event_SortDeletedTableBtnActionPerformed

    private void SortVerifiedTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortVerifiedTableBtnActionPerformed
         Voter[] sortedVoters = controller.mergeSortVerifiedByName();
    
    if (sortedVoters.length == 0) {
        JOptionPane.showMessageDialog(this, "No verified voters to sort");
        return;
    }
    
    // Load sorted data into VerifiedTable
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) VerifiedTable.getModel();
    model.setRowCount(0);
    
    for (Voter v : sortedVoters) {
        if (v != null) {
            model.addRow(new Object[]{
                v.getName(),
                v.getCitizenshipId(),
                v.getDOB(),
                v.getPhone(),
                "Verified"
            });
        }
    }
    
    JOptionPane.showMessageDialog(this, "VerifiedTable sorted by Name using Merge Sort");
    }//GEN-LAST:event_SortVerifiedTableBtnActionPerformed

    private void BinarySearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinarySearchBtnActionPerformed
    // Get search term from text field
    String searchTerm = txtSearch.getText().trim();
    
    if (searchTerm.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a search term");
        return;
    }
    
    // Get selected search option from dropdown (JComboBox)
    String searchBy = (String) cmbSearchBy.getSelectedItem();
    
    if (searchBy == null) {
        JOptionPane.showMessageDialog(this, "Please select a search option");
        return;
    }
    
    Voter foundVoter = null;
    String stats = "";
    
    // Search based on dropdown selection
    if (searchBy.equals("Name")) {
        foundVoter = controller.binarySearchByName(searchTerm);
        stats = controller.getSearchStatistics(searchTerm);
    } else if (searchBy.equals("CitizenshipID")) {        foundVoter = controller.binarySearchByCitizenshipId(searchTerm);
        stats = controller.getSearchStatisticsByCitizenshipId(searchTerm);
    }
    
    if (foundVoter == null) {
        JOptionPane.showMessageDialog(this, 
            "Voter not found!\n" + stats, 
            "Binary Search Result", 
            JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Display found voter details
    String details = "✓ VOTER FOUND using Binary Search!\n\n" +
                     "Search By: " + searchBy + "\n" +
                     "Name: " + foundVoter.getName() + "\n" +
                     "CitizenshipID: " + foundVoter.getCitizenshipId() + "\n" +
                     "Father: " + foundVoter.getFather() + "\n" +
                     "Mother: " + foundVoter.getMother() + "\n" +
                     "Grandfather: " + foundVoter.getGrandfather() + "\n" +
                     "DOB: " + foundVoter.getDOB() + "\n" +
                     "Phone: " + foundVoter.getPhone() + "\n\n" +
                     stats;
    
    JOptionPane.showMessageDialog(this, details, "Binary Search Result", JOptionPane.INFORMATION_MESSAGE);
    
    // Highlight the row in MainTable
    highlightVoterInTable(foundVoter);
}

// Helper method to highlight found voter in MainTable
private void highlightVoterInTable(Voter foundVoter) {
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) MainTable.getModel();
    
    // Find the row with matching citizenshipID
    for (int i = 0; i < model.getRowCount(); i++) {
        String citizenshipId = model.getValueAt(i, 1).toString();
        if (citizenshipId.equals(foundVoter.getCitizenshipId())) {
            MainTable.setRowSelectionInterval(i, i);
            MainTable.scrollRectToVisible(MainTable.getCellRect(i, 0, true));
            break;
        }
    }
    }//GEN-LAST:event_BinarySearchBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card2");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card4");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cmbSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSortByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSortByActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeRegisterBtnActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card3");
    }//GEN-LAST:event_homeRegisterBtnActionPerformed

    private void homeUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeUpdateBtnActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card6");
    }//GEN-LAST:event_homeUpdateBtnActionPerformed

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        CardLayout cl = (CardLayout) MainPanel.getLayout();
        cl.show(MainPanel, "card4");
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void rbDescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDescendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDescendingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewVCRS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackUpdate;
    private javax.swing.JLabel Banner;
    private javax.swing.JButton BinarySearchBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTable DeletedTable;
    private javax.swing.JButton HistoryBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTable MainTable;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton SortDeletedTableBtn;
    private javax.swing.JButton SortMainTableBtn;
    private javax.swing.JButton SortVerifiedTableBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTable VerifiedTable;
    private javax.swing.JButton VerifyBtn;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JPanel adminPanel;
    private javax.swing.ButtonGroup bgSortOrder;
    private javax.swing.JButton btnFindActionPerformed;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbSearchBy;
    private javax.swing.JComboBox<String> cmbSortBy;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton homeRegisterBtn;
    private javax.swing.JButton homeUpdateBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JRadioButton rbAscending;
    private javax.swing.JRadioButton rbDescending;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchCitizenship;
    private javax.swing.JTextField txtcitizenship;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtdob1;
    private javax.swing.JTextField txtfather;
    private javax.swing.JTextField txtfather1;
    private javax.swing.JTextField txtgrandfather;
    private javax.swing.JTextField txtgrandfather1;
    private javax.swing.JTextField txtmother;
    private javax.swing.JTextField txtmother1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
